version: "3.5"
services:
  app:
    build: .
    ports:
      - "4000:4000"
      - "3333:3333"
    volumes:
      - "./:/usr/src/app/"
      - "/usr/src/app/node_modules"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
